000000AMERICAN PRECISION        .00      .00      .00      .00        .00        .0000
1101  CASH IN BANK              .00      .00      .00      .00        .00        .000 
1110  ACCOUNTS RECEIVABLE       .00      .00      .00      .00        .00        .0000
1115  MERCHANDIS.INVENTORY      .00      .00      .00      .00        .00        .0000
1120  INSURANCS PREMIUMS   17848.71      .00      .00      .00        .00        .0000
1125  WHSE EQUIPMENT(+FRT)   989.49      .00      .00      .00        .00        .0000
1126  OFFICE EQPMNT(+FRT)       .00      .00      .00      .00        .00        .0000
1127  IMPROVEMENTS              .00      .00      .00      .00        .00        .0000
1135  PREPAID INTEREST          .00      .00      .00      .00        .00        .0000
2101  ACCTS PAY DUE CREDIT      .00      .00      .00      .00        .00        .0000
2201  SOC.SEC. TAX PAYABLE      .00      .00      .00      .00        .00        .0000
2202  FED.WITH.TAX PAYABLE      .00      .00      .00      .00        .00        .0000
2203  NYS TAX               1530.00      .00      .00      .00        .00        .0000
2204  NYC INC.TAX PAYABLE       .00      .00      .00      .00        .00        .0000
2301  ACCRUED PAYROLL(NET)      .00      .00      .00      .00        .00        .0000
2400  LOANS PAYABLE D. D. 103295.58      .00      .00      .00        .00        .0000
2410  LOANS PAYABLE       110628.45      .00      .00      .00        .00        .00  
3101  SALES INCOME              .00      .00      .00      .00        .00        .00  
3105  SALES DISCNTS/ALLOW.      .00      .00      .00      .00        .00        .00  
4101  PURCHASES FOR SALE  761656.47      .00      .00      .00        .00        .00  
4102  FREIGHT IN/OUT       70422.45      .00      .00      .00        .00        .00  
5101  PAYROLL-OFFICERS          .00      .00      .00      .00        .00        .00V 
5102  PAYROLL-OFFICE      572688.41      .00      .00      .00        .00        .00  
5103  PAYROLL-SALES             .00      .00      .00      .00        .00        .00  
5104  PAYROLL-WAREHOUSE         .00      .00      .00      .00        .00        .00  
6101  COMMISSIONS          22547.32      .00      .00      .00        .00        .00  
6102  SALES STAFF EXPENSES      .00      .00      .00      .00        .00        .00  
6103  ENTERTAINMENT EXP.     236.31      .00      .00      .00        .00        .00  
6104  AUTO OPER/MAINT EXP. 41372.54      .00      .00      .00        .00        .00  
6105  AUTO LEASE EXPENSE   21921.03      .00      .00      .00        .00        .00  
6106  ADVERTISING         167898.96      .00      .00      .00        .00        .00  
6107  SUBSCRIPTIONS       119274.51      .00      .00      .00        .00        .00  
6108  DUES                      .00      .00      .00      .00        .00        .00  
6109  TRAVEL                    .00      .00      .00      .00        .00        .00  
6110  CONVENTION EXPENSES       .00      .00      .00      .00        .00        .00  
6111  YEAR-END/XMAS EXP.    6700.00      .00      .00      .00        .00        .00  
6112  PROMOTIONAL EXPENSE   2994.70      .00      .00      .00        .00        .00  
7101  SHIPPING SUPPLIES    13454.97      .00      .00      .00        .00        .00  
7102  FREIGHT OUT(TO CUST)   800.36      .00      .00      .00        .00        .00  
7103  EXPEDITING IN WHSE.       .00      .00      .00      .00        .00        .00  
8101  RENT                129670.00      .00      .00      .00        .00        .00  
8102  ELECTRICITY          26115.45      .00      .00      .00        .00        .00  
8103  REPAIRS/MAINTENANCE  82503.38      .00      .00      .00        .00        .00  
8104  ALARM SYSTEM MAINT.   2505.69      .00      .00      .00        .00        .00  
8105  RUBBISH REMOVAL           .00      .00      .00      .00        .00        .00  
8106  OFFICE CLEANING        292.84      .00      .00      .00        .00        .00  
8107  TELEPHONE            58240.34      .00      .00      .00        .00        .00  
8108  PROFESSIONAL FEES    73652.08      .00      .00      .00        .00        .00  
8109  OFFICE EXP/SUPPLIES  84955.71      .00      .00      .00        .00        .00  
8110  POSTAGE/PARCEL POST  26271.40      .00      .00      .00        .00        .00  
8111  CLERICAL SERVICES         .00      .00      .00      .00        .00        .00  
8112  BANK CHARGES              .00      .00      .00      .00        .00        .00  
8113  EMPLOYEE HEALTH INS. 52827.65      .00      .00      .00        .00        .00  
8121  MISCELLANEOUS ITEMS  65211.32      .00      .00      .00        .00        .00  
9101  STATE INSURANCE FUND  1102.26      .00      .00      .00        .00        .00  
9102  NYS EMPLOYMENT TAX     634.22      .00      .00      .00        .00        .00  
9103  FED UNEMPLOYMENT INS      .00      .00      .00      .00        .00        .00  
8114  PAYROLL SERVICE EXP.      .00      .00      .00      .00        .00        .00  
2420  LOANS PAYABLE L.D.    6677.75      .00      .00      .00        .00        .00  
2421  LOANS PAYABLE R.F.        .00      .00      .00      .00        .00        .00  
2425  LOANS TO EMPLOYEES        .00      .00      .00      .00        .00        .00  
8115  OFFICE EQUIP REPAIRS      .00      .00      .00      .00        .00        .00  
1121  SERVICE CONTRACTS/YR   652.50      .00      .00      .00        .00        .00  
7000  CITIBANK PAYROLL TAX220477.80      .00      .00      .00        .00        .000 
8116  COMPUTER PROGRAM FEE 25173.50      .00      .00      .00        .00        .000 
8120  CASH/PETTY           31000.00      .00      .00      .00        .00        .000 
8125  PROFIT SHARING TRUST      .00      .00      .00      .00        .00        .000 
1128  COMPUTER EQUIPMENT        .00      .00      .00      .00        .00        .000 
1129  IMPROVE TO PROPERTY       .00      .00      .00      .00        .00        .0000
2422  LOAN TO JW           15083.87      .00      .00      .00        .00        .0000
7106  WHSE EQPT&RENT&LEASE      .00      .00      .00      .00        .00        .0000
7107  WHSE REPAIRS          2189.00      .00      .00      .00        .00        .0000
7104  COMPUTER REPAIR        287.11      .00      .00      .00        .00        .0000
7105  COMPUTER LEASING          .00      .00      .00      .00        .00        .0000
8117  SERV CON ON EQUIP         .00      .00      .00      .00        .00        .0000
8122  INTEREST EXPENSE          .00      .00      .00      .00        .00        .0000
8130  RENTAL EQUIPMENT       107.69      .00      .00      .00        .00        .0000
5105  PAYROLL TOM D.            .00      .00      .00      .00        .00        .0000
8135  OFFICE EXTERMINATING      .00      .00      .00      .00        .00        .0000
8140  WATER EXPENSE          728.86      .00      .00      .00        .00        .0000
8150  BUILDING TAX'S            .00      .00      .00      .00        .00        .0000
8160  STANDARD SECURITY         .00      .00      .00      .00        .00        .0000
7109  COMPUTER SUPPLIES     6174.25      .00      .00      .00        .00        .0000
8179  CREDIT&COLLECTION         .00      .00      .00      .00        .00        .0000
8100  BANK LOAN            37411.50      .00      .00      .00        .00        .0000
2401  DISTRIBUTION ACC          .00      .00      .00      .00        .00        .0000
9999  AMERICA ONE REALTY    2489.39      .00      .00      .00        .00        .0000
3                               .00      .00      .00      .00        .00        .0000
1401  CITIBANK LOAN             .00      .00      .00      .00        .00        .0000
